//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DealershipMVC.DealershipService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DealershipService.IDealershipService")]
    public interface IDealershipService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDealershipService/Dealerships", ReplyAction="http://tempuri.org/IDealershipService/DealershipsResponse")]
        DealershipModel.Entities.Dealership[] Dealerships(DealershipModel.Entities.Address address, System.Nullable<int> rangeMiles, string make, string model, string year);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDealershipService/Dealerships", ReplyAction="http://tempuri.org/IDealershipService/DealershipsResponse")]
        System.Threading.Tasks.Task<DealershipModel.Entities.Dealership[]> DealershipsAsync(DealershipModel.Entities.Address address, System.Nullable<int> rangeMiles, string make, string model, string year);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDealershipService/AddDealership", ReplyAction="http://tempuri.org/IDealershipService/AddDealershipResponse")]
        WCFStatusResponse.GenericResponse AddDealership(DealershipModel.Entities.Dealership dealership);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDealershipService/AddDealership", ReplyAction="http://tempuri.org/IDealershipService/AddDealershipResponse")]
        System.Threading.Tasks.Task<WCFStatusResponse.GenericResponse> AddDealershipAsync(DealershipModel.Entities.Dealership dealership);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDealershipService/Vehicles", ReplyAction="http://tempuri.org/IDealershipService/VehiclesResponse")]
        DealershipModel.Entities.Vehicle[] Vehicles();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDealershipService/Vehicles", ReplyAction="http://tempuri.org/IDealershipService/VehiclesResponse")]
        System.Threading.Tasks.Task<DealershipModel.Entities.Vehicle[]> VehiclesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDealershipService/VehicleFilterData", ReplyAction="http://tempuri.org/IDealershipService/VehicleFilterDataResponse")]
        System.Collections.Generic.Dictionary<string, string[]> VehicleFilterData();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDealershipService/VehicleFilterData", ReplyAction="http://tempuri.org/IDealershipService/VehicleFilterDataResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, string[]>> VehicleFilterDataAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDealershipService/Dealership", ReplyAction="http://tempuri.org/IDealershipService/DealershipResponse")]
        DealershipModel.Entities.Dealership Dealership(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDealershipService/Dealership", ReplyAction="http://tempuri.org/IDealershipService/DealershipResponse")]
        System.Threading.Tasks.Task<DealershipModel.Entities.Dealership> DealershipAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDealershipServiceChannel : DealershipMVC.DealershipService.IDealershipService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DealershipServiceClient : System.ServiceModel.ClientBase<DealershipMVC.DealershipService.IDealershipService>, DealershipMVC.DealershipService.IDealershipService {
        
        public DealershipServiceClient() {
        }
        
        public DealershipServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DealershipServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DealershipServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DealershipServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public DealershipModel.Entities.Dealership[] Dealerships(DealershipModel.Entities.Address address, System.Nullable<int> rangeMiles, string make, string model, string year) {
            return base.Channel.Dealerships(address, rangeMiles, make, model, year);
        }
        
        public System.Threading.Tasks.Task<DealershipModel.Entities.Dealership[]> DealershipsAsync(DealershipModel.Entities.Address address, System.Nullable<int> rangeMiles, string make, string model, string year) {
            return base.Channel.DealershipsAsync(address, rangeMiles, make, model, year);
        }
        
        public WCFStatusResponse.GenericResponse AddDealership(DealershipModel.Entities.Dealership dealership) {
            return base.Channel.AddDealership(dealership);
        }
        
        public System.Threading.Tasks.Task<WCFStatusResponse.GenericResponse> AddDealershipAsync(DealershipModel.Entities.Dealership dealership) {
            return base.Channel.AddDealershipAsync(dealership);
        }
        
        public DealershipModel.Entities.Vehicle[] Vehicles() {
            return base.Channel.Vehicles();
        }
        
        public System.Threading.Tasks.Task<DealershipModel.Entities.Vehicle[]> VehiclesAsync() {
            return base.Channel.VehiclesAsync();
        }
        
        public System.Collections.Generic.Dictionary<string, string[]> VehicleFilterData() {
            return base.Channel.VehicleFilterData();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, string[]>> VehicleFilterDataAsync() {
            return base.Channel.VehicleFilterDataAsync();
        }
        
        public DealershipModel.Entities.Dealership Dealership(int id) {
            return base.Channel.Dealership(id);
        }
        
        public System.Threading.Tasks.Task<DealershipModel.Entities.Dealership> DealershipAsync(int id) {
            return base.Channel.DealershipAsync(id);
        }
    }
}
